
#type: args

train:
  epochs: 50
  batch_size: 16
  lr: 0.0005

diffusion:
  layers: 4  
  channels: 64 
  nheads: 2 #4
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 150
  schedule: "quad"
  mixed: False

model:
  is_unconditional: 0
  timeemb: 32
  featureemb: 16
  target_strategy: "random"
  mixed: False

